## 01실습

다음의 ages를 bins의 구간으로 나누어 보세요. (hint. pd.cut()을 사용하세요.)
```
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]

```


In [3]:
import pandas as pd

ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]

pd.cut(ages, bins)

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

# 02실습

다음과 같은 물고기의 크기와 관련된 데이터가 있다. 

```
fish_data = np.array([2,3,3,4,4,4,4,5,5,6])
fish_data
```



In [4]:
import numpy as np
fish_data = np.array([2,3,3,4,4,4,4,5,5,6])
fish_data

array([2, 3, 3, 4, 4, 4, 4, 5, 5, 6])

1. fish_data의 합계와 fish_data의 사이즈를 구하시오. (np.sum(), len()) 

In [5]:
np.sum(fish_data), len(fish_data)

(40, 10)

2. fish_data 의 평균을 구하시오.

In [6]:
np.sum(fish_data)/len(fish_data)

4.0

In [7]:
np.mean(fish_data)

4.0

3. fish_data의 중위수(중앙값)을 구하시오.

In [8]:
np.median(fish_data)

4.0

4. fish_data 의 최빈값을 구하시오.

In [9]:
from scipy import stats
stats.mode(fish_data)

ModeResult(mode=array([4]), count=array([4]))

In [10]:
pd.Series(fish_data).mode()

0    4
dtype: int32

# 03실습

다음과 같은 물고기의 크기와 관련된 데이터가 있다. 

```
fish_data = np.array([2,3,3,4,4,4,4,5,5,6])
fish_data
```



In [9]:
import numpy as np

fish_data = np.array([2,3,3,4,4,4,4,5,5,6])
fish_data

array([2, 3, 3, 4, 4, 4, 4, 5, 5, 6])

1. fish_data 의 분산을 구하시오

In [10]:
fish_data.var(ddof=0)
# 또는
np.var(fish_data)

1.2

2. fish_data의 불편분산을 구하시오.

In [11]:
fish_data.var(ddof=1)
# 또는
np.var(fish_data, ddof=1)

1.3333333333333333

3. fish_data의 표준편차를 구하시오.

In [12]:
fish_data.std()
# 또는
np.std(fish_data)

1.0954451150103321

4. fish_data의 사분위수를 구하시오.

In [13]:
Q1,Q2,Q3 = np.percentile(fish_data, [25, 50, 75])
print(Q1, Q2, Q3)

3.25 4.0 4.75


5. fish_data의 IQR값을 구하시오.

In [14]:
IQR = Q3 - Q1
IQR

1.5

# 04실습 

다음과 같이 물고기의 크기와 무게에 관련된 데이터가 있다.

```
data = pd.DataFrame({'length':[18.5, 18.7, 19.1, 19.7, 21.5, 21.7, 21.8, 22. , 23.4, 23.8], 
                     'weight':[34, 39, 41, 38, 45, 41, 52, 44, 44, 49]})
data
```

In [15]:
data = pd.DataFrame({'length':[18.5, 18.7, 19.1, 19.7, 21.5, 21.7, 21.8, 22. , 23.4, 23.8], 
                     'weight':[34, 39, 41, 38, 45, 41, 52, 44, 44, 49]})
data

length  weight
0    18.5      34
1    18.7      39
2    19.1      41
3    19.7      38
4    21.5      45
5    21.7      41
6    21.8      52
7    22.0      44
8    23.4      44
9    23.8      49

1. 물고기 데이터에서 length와 weight 간의 공분산을 구하시오.

In [16]:
np.cov(data.length, data.weight)

array([[ 3.64622222,  7.67333333],
       [ 7.67333333, 28.01111111]])

In [17]:
data.cov()

length     weight
length  3.646222   7.673333
weight  7.673333  28.011111

2. 물고기 데이터에서  length와 weight 간의 상관계수를 구하시오.

In [18]:
np.corrcoef(data.length, data.weight)

array([[1.       , 0.7592719],
       [0.7592719, 1.       ]])

In [19]:
data.corr()

length    weight
length  1.000000  0.759272
weight  0.759272  1.000000

# 06.실습



1. 10개의 제비중에 4개의 당첨 제비가 포함되어 있다. 이 중 3개의 제비를 임의로 뽑을 때 다음을 구하시오.

    1) 3개 모두가 당첨 제비가 아닐 확률은?  
    2) 적어도 1개 이상이 제비일 확률은?

In [1]:
from itertools import combinations

lottery = list(combinations([1,1,1,1,0,0,0,0,0,0], 3))
N = len(list(lottery))

In [3]:
len(lottery)

120

In [23]:
wins = 0

for i in lottery:
    if (i.count(0) == 3):
        wins += 1

print('3개 모두가 당첨 제비가 아닐 확률 = ', wins/N)

3개 모두가 당첨 제비가 아닐 확률 =  0.16666666666666666


In [24]:
wins = 0

for i in lottery:
    if (i.count(1) == 1) or (i.count(1) == 2) or (i.count(1) == 3):
        wins += 1

print('적어도 1개 이상이 당첨 제비일 확률 = ', wins/N)

적어도 1개 이상이 당첨 제비일 확률 =  0.8333333333333334


In [25]:
# 여사건의 확률 
1-(20/120)

0.8333333333333334

In [26]:
# 3개 모두가 당첨 제비가 아닐 확률 
from scipy.special import comb

comb(4,0)*comb(6,3)/comb(10, 3)

0.16666666666666666

In [27]:
# 적어도 1개 이상이 당첨 제비일 확률
1 - (comb(4,0)*comb(6,3)/comb(10, 3))

0.8333333333333334

# 07 실습

1. 조건부 확률을 이용하여 다음 확률을 계산해 보자.  

1000명 중 5명이 걸린다고 하자. 병원에서 이 병에 걸렸는지 판정하는 검사도구를 개발했는데,   
> 검사의 정확도는 '실제로 병이 있는 경우에 병이 있다고 정확히 진단할 확률'이 95%이고, '실제로 병이 없는 경우에 병이 없다고 정확히 판정할 확률'이 99%라고 하자. 

어떤 사람이 검사를 받은 결과 병이 있는 것으로 양성판정을 받았을 때, 이 사람이 실제로 병에 걸려 있을 확률은 얼마나 될까?

In [1]:
p_병 = 0.005 # 병에 걸렸을 확률, 유병률

p_민감도 = 0.95 # 병이 있는 경우에, 병이 있다고 판정할 확률
p_특이도 = 0.99 # 병이 없는 경우에, 병이 없다고 판정할 확률

# 병이 없는 경우에, 병이 있다고 판정할 확률 = 1 - 특이도 = 0.01
# p_양성 ==> 병 유무와 관계없이 양성이 나올 확률
# p_양성 = 병에 걸려서 양성 + 병에 안걸렸는데 양성
p_양성 = p_병 * 0.95 + (1 - p_병) * 0.01

p_병_양성 = (0.95 * 0.005) / p_양성  # 이 사람이 실제로 병에 걸려 있을 확률

p_병_양성  

0.32312925170068024

2. A라는 사람이 다시 한번 검사 하였을때 2차 검사에서도 양성 판정을 받았다면 실제로 이 병에 걸렸을 확률은 얼마인가?

In [2]:
# p_양성은 검사결과 양성 판정이 나올 확률이다. 
# 병에 걸릴 확률 p_병은 아무런 관찰이 없을때 가정한 0.005가 아니라 
# 이전 검사결과를 토대로 구한 사후 확률인 p_병_양성으로 업데이트 된다. 
# 1번에서 구한 p_양성, p_민감도, p_병 의 확률을 사용하여 사후확률을 계산한다. 

p_병 = p_병_양성 

p_양성 = p_병 * 0.95 + (1 - p_병) * 0.01

p_병_양성 = (0.95 * p_병) / p_양성

p_병_양성 

0.9784258456201215

1차, 2차 모두 양성일 경우 병에 걸렸을 확률은 98%로 매우 높다. 

# 10실습

1. 복권의 당첨률이 30% 라고 한다. 복권을 8장 구입했다. 이항분포로 다음의 확률을 구하시오.
    - 4장이 당첨될 확률은? ($P=4$)
    - 3장에서 7장 당첨될 확률은? ( $P(3\le X \le 7$ )
    - 6장 이상 당첨될 확률은? ( $P \ge 6$ )

In [30]:
rv = stats.binom(8, 0.3)
rv.pmf(4), rv.cdf(7)-rv.cdf(2), 1-rv.cdf(5)

(0.13613669999999994, 0.4481605799999997, 0.011292210000000025)

# 11실습

1. 확률변수 X가 평균이 70, 표준편차가 10인 정규분포를 따를때 다음의 확률을 구하시오.
    
    - P(X < 94.3)
    - P(X > 57.5)
    - P(57.7 < X < 94.3)

In [31]:
rv = stats.norm(loc = 70, scale=10)

rv.cdf(94.3), 1-rv.cdf(57.5), rv.cdf(94.3)-rv.cdf(57.5)

(0.9924505885836908, 0.8943502263331446, 0.8868008149168355)